messages/messages.json, src/commands/auth/jwt/grant.ts, src/commands/auth/logout.ts, src/commands/auth/sfdxurl/store.ts, src/prompts.ts, test/commands/auth/jwt/grant.test.ts, test/commands/auth/sfdxurl/store.test.ts
`auth:jwt:grant` and `auth:sfdxurl:store` now prompt users before executing when the CLI is in demo mode
@W-8141101@
=> feat: handle demo mode

messages/device.login.json, messages/jwt.grant.json, messages/logout.json, messages/messages.json, messages/sfdxurl.store.json, messages/web.login.json, package.json, src/commands/auth/device/login.ts, src/commands/auth/jwt/grant.ts, src/commands/auth/sfdxurl/store.ts, src/commands/auth/web/login.ts, src/common.ts, src/prompts.ts, test/commands/auth/device/login.test.ts, test/commands/auth/logout.test.ts, test/commands/auth/web/login.test.ts, yarn.lock
Adds the `auth:web:login` command
Depends on https://github.com/forcedotcom/sfdx-core/pull/313
@W-7824743@
=> feat: add auth:web:login

messages/jwt.grant.json, messages/logout.json, messages/sfdxurl.store.json, messages/web.login.json, package.json
Updates help output
@W-8246223@
=> chore: update help output

src/commands/auth/jwt/grant.ts, tsconfig.json
=> fix: jwt grant error message

.circleci/config.yml, .idea/workspace.xml, test/commands/auth/logout.test.ts, yarn.lock
bumps the npm release orb to v4
=> fix: bumped npm release to v4 @W-8437381@

.github/dependabot.yml
=> chore: sync dependabot.yml

messages/jwt.grant.json, messages/web.login.json
Adds help to auth:jwt:grant about specifying a sandbox.  adds help to auth:web:login about specifying a my domain URL (and not to use lightning domains format)
@W-8821915@
=> fix: update help w/info about my domain URLs and sandboxes

.circleci/config.yml
=> chore: @W-0@ fix indent and merge sm/nuts-with-circle

.github/dependabot.yml
Test to see if major version are excluded for all deps
@W-0@
=> chore: exclude major version bumps

messages/accesstoken.store.json
edits help for auth:accesstoken:store
@W-9517030@
=> fix: edit help for auth:accesstoken:store

messages/device.login.json, messages/jwt.grant.json, messages/web.login.json
Updates https://test.salesforce.com to https://MyDomainName--SandboxName.sandbox.my.salesforce.com, for security reasons
@W-9561593@
=> fix: update sandbox URL to be more secure

LICENSE.txt, package.json, yarn.lock
=> feat: bump deps

package.json, yarn.lock
uses `oclif` not `@oclif/dev-cli`
=> chore: update oclif-dev to oclif

package.json, yarn.lock
Bumps core v3 to latest, https://github.com/forcedotcom/sfdx-core/pull/560
@W-10999290@
=> chore: bump `@salesforce/core`

src/commands/auth/logout.ts
Use the instance of `ConfigAggregator` on `SfdxCommand`
@W-11025387@
=> fix: use configAgg on command

messages/accesstoken.store.json, messages/device.login.json, messages/jwt.grant.json, messages/logout.json, messages/sfdxurl.store.json, messages/web.login.json
Adds "$" prompt to examples so that it's tagged correctly in the DITA files when generating the CLI REF.
@W-11159165@
=> Add prompt to example in messages

package.json, yarn.lock
=> fix: bump sfdx-core

.gitignore, package.json, test/commands/auth/device/login.test.ts, test/commands/auth/scratch-identify.nut.ts, yarn.lock
=> chore: bump deps

src/commands/auth/accesstoken/store.ts, src/commands/auth/device/login.ts, src/commands/auth/jwt/grant.ts, src/commands/auth/sfdxurl/store.ts, src/commands/auth/web/login.ts, test/commands/auth/web/login.test.ts, yarn.lock
add missing alias for 'setdefaultdevhubusername'
@W-12484720@
=> fix: add missing flag aliases 'setdefaultdevhubusername'

test/commands/scratch-identify.nut.ts
mainly bumps deps to latest testkit
=> fix: fix NUTs

package.json, test/commands/org/login/login.web.test.ts, yarn.lock
removes plugin-config dep for plugin-settings
@W-12709387@
=> chore: remove plugin-config dep

messages/logout.md
doc improvement based on gh issue feedback
@W-13192405@https://github.com/forcedotcom/cli/issues/2128
=> docs: message about default org logout

test/commands/scratch-identify.nut.ts
NUTs only: remove sfdx reference
https://github.com/salesforcecli/cli/actions/runs/5086600127/jobs/9141806884
=> test: remove sfdx executable

src/commands/org/login/web.ts
Adds the original error stack to the error that gets thrown for easier debugging.
=> fix: add the original error stack to the new error

messages/messages.md
The My Domain CX writer requested changes to the --instance-url description, I did what I could. 
@W-@
=> fix: adds a bit of formatting, as requested by MyDomain writer

package.json, yarn.lock
bump sfdx-core to get the preflight fix for web login commands.
@W-15313611@
=> fix: bump salesforce/core

src/common.ts
let sfdx-core define lightning domains in one place (sfdcUrl)
@W-15153669@
=> feat: lightning url check from sfdx-core

package.json, src/commands/org/login/device.ts, test/commands/org/login/login.device.test.ts, yarn.lock
import from top-level export, not lib
https://github.com/forcedotcom/sfdx-core/actions/runs/8607831921/job/23589125074?pr=1050#step:12:11
=> fix: don't do deep imports from sfdx-core

package.json, yarn.lock
=> fix(deps): bump plugin-info for doctor

package.json, yarn.lock
dep bumps
https://github.com/salesforcecli/cli/actions/runs/9324482843/job/25669790838?pr=1703#step:6:98
=> fix(deps): bump plugins-core and inquirer

package.json, src/commands/org/logout.ts, src/common.ts, yarn.lock
logout L183 drops the "bold" because that was the only thing left using the dep
=> fix(deps): remove chalk

messages/accesstoken.store.md
changes old SFDX env var to its SF equiv
@W-16267578@
=> fix: message contains old SFDX_ env var

src/commands/org/list/auth.ts, yarn.lock
=> chore: review code

messages/web.login.md
=> W-18763411: Update help for "org login web" to doc multiple client app links

messages/web.login.md, src/commands/org/login/web.ts, test/commands/org/login/login.web.test.ts
update error message when using web auth in container mode
=> fix: update device message

README.md, package.json, test/commands/org/login/login.web.test.ts, yarn.lock
Adds support for code builder web auth.
@W-19380836@
=> feat: support codebuilder ca auth - W-19380836
