salesforcecli/plugin-auth

- messages/list.json
- messages/messages.json
- messages/sfdxurl.store.json
- package.json
- src/commands/auth/device/login.ts
- src/commands/auth/jwt/grant.ts
- src/commands/auth/list.ts
- src/commands/auth/sfdxurl/store.ts
- src/commands/auth/web/login.ts
- src/prompts.ts
- Dims prompts
- Removes `%s` from demo mode prompts
- Returns decrypted auth fields for `device:login`, `web:login`, `jwt:grant`, and `sfdxurl:store`
- `auth:list` returns "No results found" when no auth files exist
Depends on https://github.com/forcedotcom/sfdx-core/pull/321
@W-8247994@
@W-8247935@
@W-8248004@
@W-8248034@
> fix: various bugs

- src/commands/auth/device/login.ts
- src/commands/auth/jwt/grant.ts
- src/commands/auth/list.ts
- src/commands/auth/logout.ts
- src/commands/auth/sfdxurl/store.ts
- src/commands/auth/web/login.ts
Aliases the old auth commands in the `force` namespace
@W-8039212@
> feat: alias old commands in force namespace

- src/commands/auth/device/login.ts
- test/commands/auth/device/login.test.ts
Fixes issue with `auth:device:login` when `instanceurl` flag is provided
> fix: device login with instanceurl

- package.json
- src/commands/auth/list.ts
- test/.eslintrc.js
- test/commands/auth/device/login.test.ts
- test/commands/auth/jwt/grant.nut.ts
- test/commands/auth/jwt/grant.test.ts
- test/commands/auth/list.nut.ts
- test/commands/auth/list.test.ts
- test/commands/auth/logout.nut.ts
- test/commands/auth/logout.test.ts
- test/commands/auth/sfdxurl/store.nut.ts
- test/commands/auth/sfdxurl/store.test.ts
- test/commands/auth/web/login.test.ts
- test/testHelper.ts
- yarn.lock
- Adds NUTs for `auth:list`, `auth:logout`, `auth:jwt:grant`, and `auth:sfdxurl:store`
This PR does NOT add any tests for `auth:web:login` or `auth:device:login` since we do not want to mock interactions with a web browser
@W-8856588@
Depends on https://github.com/salesforcecli/cli-plugins-testkit/pull/32
> test: add NUTs

- src/commands/auth/sfdxurl/store.ts
- test/commands/auth/sfdxurl/store.test.ts
Fixes a regression with error messages
You should now see this when encountering errors parsing or finding an sfdxAuthUrl in a json or txt file.
@W-9020997@
> fix(sfdxauthurl): error handling regression

- .circleci/config.yml
- messages/messages.json
- src/common.ts
- test/common.test.ts
Prevent CLI users from using lightning domain URLs in sfdx
@W-5494117@
> fix: test for lightning instance url

- messages/device.login.json
Adds back missing command description that was lost when the auth commands were broken out into their own plugin.  
NOTE: I used this old version of the CLI Reference when searching for missing content: https://developer.salesforce.com/docs/atlas.en-us.224.0.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_auth.htm#cli_reference_device_login
@W-10049649@
> fix: add missing long command description

- README.md
- src/commands/auth/accesstoken/store.ts
The short flag `s` was currently assigned to two flags.
This change now aligns the short form of the flags
with other commands of this plugin:
- `s` for `setdefaultusername`
- `d` for `setdefaultdevhubusername`
The short flag `-s` was setting the `defaultdevhubusername` config instead of `setdefaultusername`.
> fix: use `d` as short form of `setdefaultdevhubusername` flag

- src/common.ts
sets `isDevHub` in the auth file 
@W-10811265@
https://github.com/forcedotcom/cli/issues/1423
> fix: set isDevHub when --setdefaultdevhubusername is passed

- .circleci/config.yml
set node to lts for `test-and-release` CI Job
> chore: use node LTS for t+r

- .circleci/config.yml
> fix: use node 14 explicitly

- command-snapshot.json
- messages/web.login.json
- src/commands/auth/web/login.ts
Add support for targeting browser in login command
https://github.com/forcedotcom/cli/issues/1465
> feat: support targeting browser in login command

- src/commands/auth/list.ts
Fix the list printing empty table when no auth'd orgs are found
https://github.com/forcedotcom/cli/issues/1796
As suggested by @cristiand391, I've simply added a check for the length of the array returned by AuthInfo.listAllAuthorizations to avoid relying on the error to be throw thrown.
> fix(list): empty list when no authed orgs are found

- LICENSE.txt
- package.json
- src/commands/auth/list.ts
- yarn.lock
Uses sf-plugins-core v2 and oclif/core v2
@W-10791948@
> feat: use latest oclif/core

- .mocharc.json
- src/common.ts
- test/common.test.ts
allows foo-lightning.my.salesforce.com login urls
@W-13639832@
https://github.com/forcedotcom/cli/issues/2241
> fix: regex lightning is surrounded by period

- messages/messages.md
See internal slack thread:
https://salesforce-internal.slack.com/archives/G02K6C90RBJ/p1691780187618929
If you pass `--client-id` to use a custom connected app, `org login web` will prompt for the client secret but this can be skipped if `Require Secret for Web Server Flow enabled` is turned off in the app.
This PR updates the prompt msg to ask the user to just press enter if that's the case, the internal user confirmed this works.
@W-13943313@
> chore: update client secret prompt msg

- src/commands/org/login/sfdx-url.ts
@W-14085765@ will make AuthInfo.getFields readonly.  Preemptively prepare for that change so that we don't have to do it later and so that auth's tests can be used to valid the bigger configFile change safety.
> refactor: not  mutate authinfo.getFields object

- src/commands/org/login/device.ts
- src/commands/org/login/web.ts
import 1 type from sfdx-core instead of jsforce
https://github.com/forcedotcom/sfdx-core/actions/runs/6535843735/job/17792534010
> refactor(types): remove jsforce imports

- command-snapshot.json
- messages/sfdxurl.store.md
- src/commands/org/login/sfdx-url.ts
- test/commands/org/login/login.sfdx-url.test.ts
- oclif has been updated to include a new option for flags: `allowStdin`
- Another oclif update allows a flag to be designated as stdin 'only', meaning that it will error out if anything other than the '-' value is provided
- A new flag has been introduced per recommendation called `--sfdx-url-stdin` and has `allowStdin: 'only'`
- This means `--sfdx-url-file` is no longer required, so an error is thrown if neither `--sfdx-url-stdin` or `--sfdx-url-file` are given
- Original discussion on this solution found here: https://github.com/oclif/core/issues/761
`$ echo url | sf org login sfdx-url --sfdx-url-stdin -`
closes: https://github.com/forcedotcom/cli/issues/2120
> feat: allow stdin for sfdx-url

- command-snapshot.json
- messages/sfdxurl.store.md
- src/commands/org/login/sfdx-url.ts
- test/commands/org/login/login.sfdx-url.test.ts
Merges #886 
* feat: allow stdin for sfdx-url
* Update messages/sfdxurl.store.md
* Update messages/sfdxurl.store.md
* Update messages/sfdxurl.store.md
* Update messages/sfdxurl.store.md
* feat: create new --sfdx-url-stdin flag
* feat: remove unnecessary error
* feat: allowStdin set to 'only'
* Update messages/sfdxurl.store.md
* feat: add suggestions to make flags exclusive and required
* feat: remove exclusive option, as it is implied with exactlyOne
* Update messages/sfdxurl.store.md
---------
> feat: allow stdin for sfdx-url (#886)

- src/commands/org/logout.ts
- test/commands/org/logout.test.ts
fix logout confirmation messages
https://github.com/forcedotcom/cli/issues/2671
@W-14903300@
> fix: logout confirmation messages

- messages/sfdxurl.store.md
Updates help after "-" no longer required for --sfdx-url-stdin flag
@W-@
> fix: update help after "-" no longer required for --sfdx-url-stdin

- package.json
- yarn.lock
Bumps the `open` library to the new major version, v10.1.0 so that Windows users can define the shell to use for the command.
@W-15235605@
[spawn EPERM error on Windows if user does not have powershell access](https://github.com/forcedotcom/cli/issues/2768)
> feat: bump to new major version of the open lib

- messages/sfdxurl.store.md
hard codes part of the piping-URL example so that it renders correctly in the generated Command Reference.  This hard codes a "$" prompt in the DITA, which is frowned upon by CX, but because this is an exception to how we normally print the examples, I'm gonna allow it just this once. 
@W-15454019@
> fix: typo in piping URL example

- src/commands/org/login/jwt.ts
- test/commands/org/login/login.jwt.nut.ts
- test/commands/org/login/login.jwt.test.ts
Wraps any error that happens during JWT auth in a JwtGrantError to retain the original cause and stack.  Augments existing unit test.  Adds new NUT.
@W-16395441@
To test:
Use a current version of the CLI to `org login jwt` with an incorrect client ID using `--json` and without `--json`.  Note the result and compare with a locally built plugin-auth.  The fixed plugin should retain all the error information and include an error `cause`.
> fix: wrap JwtGrantErrors

- messages/sfdxurl.store.md
- src/commands/org/login/sfdx-url.ts
- test/commands/org/login/login.sfdx-url.test.ts
Updates info about SFDX auth URL to explain that the auth still happens over HTTPS, even though the auth url starts with "force://".   
@W-16716321@
> clarify help for "org login sfdx-url" regarding force:// vs. https://

- src/commands/org/login/web.ts
- test/commands/org/login/login.web.test.ts
add `SF_` to another SFDX_ env
> fix: use SF envs for container mode

- messages/web.login.md
- src/commands/org/login/web.ts
Check if the child process returned by `open` in `org login web` emits the `exit` event and throw if it includes an exit code > 0 (the platform-dependant open command failed to open the browser).
On macos, we get the following error:
```
➜  ~ open -a 'microsoft edge'
Unable to find application named 'microsoft edge'
```
but no `error` event is emitted and `exit` only includes the exit code so we can't offer more info about why `open` failed.
docs:
https://nodejs.org/api/child_process.html#event-exit
https://github.com/forcedotcom/cli/issues/1830
@W-17969693@
> fix(web login): throw if can't open browser W-17969693

- command-snapshot.json
- messages/logout.md
- messages/web.login.md
- package.json
- schemas/org-login-access__token.json
- schemas/org-login-device.json
- schemas/org-login-jwt.json
- schemas/org-login-sfdx__url.json
- schemas/org-login-web.json
- src/commands/org/login/web.ts
- src/commands/org/logout.ts
- test/commands/org/login/login.jwt.test.ts
- yarn.lock
Part of. https://github.com/forcedotcom/sfdx-core/pull/1188
* Adds a new `--scopes` flag to allow specify requested API scopes (same as `SFDX_AUTH_SCOPES` env var)
* adds `--app`/`--username` flags for "link-app" mode
@W-18394868@
> feat: `org login web` support for multi auth W-18394868

- messages/logout.md
- src/commands/org/logout.ts
- test/commands/org/login/login.jwt.nut.ts
- test/commands/org/logout.test.ts
Remove warning message
throw an error when user using `org logout `without authenticated org correctly.
@W-19385476@
warning PR: https://github.com/salesforcecli/plugin-auth/pull/1282
> fix org logout with fail username/alias-W-19385476
